language: php
php:
    - 7.2
    - 7.3

install:
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/tester tests -s -p php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
